import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import axios from '../lib/axios'
import useAuthStore from '../store/authStore'
const colors = { running: '#22c55e', planned: '#38bdf8', on_hold: '#f59e0b', completed: '#a78bfa' }
export default function FactoryDashboard() {
  const { user } = useAuthStore(); const navigate = useNavigate(); const [orders, setOrders] = useState([]); const [error, setError] = useState('')
  const load = async () => { try { setOrders((await axios.get('/production-orders')).data) } catch { setError('Could not load production orders.') } }
  useEffect(() => { if (!user) navigate('/login'); else load() }, [user])
  const metrics = useMemo(() => { const target = orders.reduce((a,o)=>a+o.target,0), actual = orders.reduce((a,o)=>a+o.actual,0), defects = orders.reduce((a,o)=>a+o.defects,0), wip = orders.reduce((a,o)=>a+o.wip,0); return { target, actual, defects, wip, efficiency: target ? Math.round(actual / target * 100) : 0, quality: actual ? (100 - defects / actual * 100).toFixed(1) : 0 } }, [orders])
  return <div style={{ minHeight: '100vh', background: '#0d1117', color: 'white', padding: '36px max(24px, calc((100vw - 1180px)/2))' }}><p style={{ color: '#fb923c', fontWeight: 800, margin: 0 }}>CONNECTED OPERATIONS · MES</p><h1 style={{ fontSize: 32, margin: '8px 0' }}>Factory command center</h1><p style={{ color: '#94a3b8' }}>Live production visibility for output, quality, WIP and bottlenecks.</p>{error && <p style={{ color: '#fca5a5' }}>{error}</p>}<div style={{ display: 'grid', gridTemplateColumns: 'repeat(5,1fr)', gap: 12, margin: '24px 0' }}>{[['Output',`${metrics.actual.toLocaleString()} / ${metrics.target.toLocaleString()}`],['Efficiency',`${metrics.efficiency}%`],['First-pass quality',`${metrics.quality}%`],['Work in process',metrics.wip],['Open lines',orders.filter(o=>o.status === 'running').length]].map(([k,v])=><div key={k} style={{ padding: 18, borderRadius: 12, background: '#172233', border: '1px solid #26354a' }}><p style={{ color: '#94a3b8', fontSize: 12, margin: 0 }}>{k}</p><strong style={{ fontSize: 22, display: 'block', marginTop: 8 }}>{v}</strong></div>)}</div><section style={{ background: '#111b29', borderRadius: 16, overflow: 'hidden', border: '1px solid #26354a' }}><div style={{ padding: '16px 20px', borderBottom: '1px solid #26354a', fontWeight: 800 }}>Production orders</div>{orders.length === 0 ? <div style={{ padding: 32, color: '#94a3b8' }}>No production data yet. Load the demo workspace from Style Workflow.</div> : <div style={{ overflowX: 'auto' }}><table style={{ borderCollapse: 'collapse', width: '100%', minWidth: 700 }}><thead style={{ color: '#94a3b8', fontSize: 12, textAlign: 'left' }}><tr>{['Order','Style','Line','Progress','WIP','Quality','Status'].map(h=><th key={h} style={{ padding: 14 }}>{h}</th>)}</tr></thead><tbody>{orders.map(order=>{const progress=order.target?Math.round(order.actual/order.target*100):0;return <tr key={order._id} style={{ borderTop: '1px solid #26354a' }}><td style={{ padding: 14, color: '#fb923c', fontWeight: 800 }}>{order.orderNumber}</td><td style={{ padding: 14 }}>{order.styleName}</td><td style={{ padding: 14 }}>{order.line}</td><td style={{ padding: 14, minWidth: 150 }}><div style={{ height: 7, background: '#26354a', borderRadius: 99 }}><div style={{ height: '100%', width: `${Math.min(progress,100)}%`, background: '#22c55e', borderRadius: 99 }}/></div><small style={{ color: '#94a3b8' }}>{order.actual}/{order.target} ({progress}%)</small></td><td style={{ padding: 14 }}>{order.wip}</td><td style={{ padding: 14 }}>{order.actual ? (100 - order.defects/order.actual*100).toFixed(1) : 0}%</td><td style={{ padding: 14 }}><span style={{ color: colors[order.status], textTransform: 'capitalize', fontWeight: 700 }}>{order.status.replace('_',' ')}</span></td></tr>})}</tbody></table></div>}</section></div>
}
