import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import axios from '../lib/axios'
import useAuthStore from '../store/authStore'

const statuses = ['draft', 'pattern', 'fit_review', 'approved', 'production']
const label = value => value.replace('_', ' ').replace(/\b\w/g, character => character.toUpperCase())
const chip = status => ({ draft: '#64748b', pattern: '#38bdf8', fit_review: '#f59e0b', approved: '#22c55e', production: '#a78bfa' }[status] || '#64748b')
export default function Styles() {
  const { user } = useAuthStore(); const navigate = useNavigate(); const [styles, setStyles] = useState([]); const [search, setSearch] = useState(''); const [filter, setFilter] = useState(''); const [showForm, setShowForm] = useState(false); const [notice, setNotice] = useState(''); const [notifications, setNotifications] = useState([]); const [showNotifications, setShowNotifications] = useState(false); const [form, setForm] = useState({ name: '', styleNumber: '', season: 'Spring 2026', brand: '', category: '', status: 'draft', tags: '' })
  const load = async () => { try { const { data } = await axios.get('/styles', { params: { search, status: filter || undefined } }); setStyles(data) } catch { setNotice('Could not load styles. Please sign in again.') } }
  useEffect(() => { if (!user) navigate('/login'); else load() }, [user, search, filter])
  const create = async e => { e.preventDefault(); try { await axios.post('/styles', { ...form, tags: form.tags.split(',').map(x => x.trim()).filter(Boolean) }); setShowForm(false); setForm({ name: '', styleNumber: '', season: 'Spring 2026', brand: '', category: '', status: 'draft', tags: '' }); load() } catch (err) { setNotice(err.response?.data?.message || 'Could not create the style') } }
  const move = async (style, status) => { try { await axios.put(`/styles/${style._id}`, { status }); load() } catch (err) { setNotice(err.response?.data?.message || 'Could not update the style') } }
  const seed = async () => { try { const { data } = await axios.post('/demo/seed'); setNotice(data.message); load() } catch (err) { setNotice(err.response?.data?.message || 'Could not load demo data') } }
  const loadNotifications = async () => { try { setNotifications((await axios.get('/notifications')).data); setShowNotifications(true) } catch { setNotice('Could not load notifications') } }
  const requestReview = async style => { try { await axios.post(`/styles/${style._id}/reviews`, { reviewerId: user._id, reviewerName: user.name }); setNotice(`Review requested for ${style.styleNumber}`); load() } catch (err) { setNotice(err.response?.data?.message || 'Could not request review') } }
  const decide = async (style, decision) => { try { await axios.post(`/styles/${style._id}/reviews/decision`, { decision, note: decision === 'approved' ? 'Fit and details approved.' : 'Please revise the submitted sample.' }); setNotice(`Review ${decision.replace('_', ' ')}`); load() } catch (err) { setNotice(err.response?.data?.message || 'Request a review before deciding.') } }
  return <div style={{ minHeight: '100vh', background: '#0d1117', color: 'white', padding: '36px max(24px, calc((100vw - 1280px)/2))' }}>
    <div style={{ display: 'flex', justifyContent: 'space-between', gap: 16, alignItems: 'start', flexWrap: 'wrap' }}><div><p style={{ color: '#fb923c', fontWeight: 800, margin: 0 }}>TUKACLOUD · PRODUCT DEVELOPMENT</p><h1 style={{ fontSize: 32, margin: '8px 0' }}>Style workflow</h1><p style={{ color: '#94a3b8', margin: 0 }}>From product concept to production-ready approval.</p></div><div style={{ display: 'flex', gap: 10 }}><button onClick={loadNotifications} style={{ background: '#243247', color: 'white', border: '1px solid #475569', borderRadius: 10, padding: '11px 14px', fontWeight: 700 }}>Notifications{notifications.filter(n => !n.read).length ? ` (${notifications.filter(n => !n.read).length})` : ''}</button><button onClick={seed} style={{ background: '#243247', color: 'white', border: '1px solid #475569', borderRadius: 10, padding: '11px 14px', fontWeight: 700 }}>Load demo workspace</button><button onClick={() => setShowForm(true)} style={{ background: '#ea580c', color: 'white', border: 0, borderRadius: 10, padding: '11px 14px', fontWeight: 800 }}>+ New style</button></div></div>
    {notice && <div style={{ marginTop: 16, padding: 12, borderRadius: 10, color: '#fed7aa', background: '#431407' }}>{notice}</div>}
    <div style={{ display: 'flex', gap: 10, margin: '26px 0', flexWrap: 'wrap' }}><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search style number, name or tag" style={{ minWidth: 250, flex: 1, padding: 12, borderRadius: 10, border: '1px solid #334155', background: '#172233', color: 'white' }} /><select value={filter} onChange={e => setFilter(e.target.value)} style={{ padding: 12, borderRadius: 10, border: '1px solid #334155', background: '#172233', color: 'white' }}><option value="">All stages</option>{statuses.map(s => <option key={s} value={s}>{label(s)}</option>)}</select></div>
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(5,minmax(210px,1fr))', gap: 14, overflowX: 'auto' }}>{statuses.map(status => <section key={status} style={{ minWidth: 210, background: '#111b29', padding: 12, borderRadius: 14, borderTop: `3px solid ${chip(status)}` }}><h2 style={{ margin: '3px 0 14px', fontSize: 15 }}>{label(status)} <span style={{ color: '#64748b' }}>{styles.filter(x => x.status === status).length}</span></h2>{styles.filter(x => x.status === status).map(style => <article key={style._id} style={{ background: '#172233', padding: 14, borderRadius: 10, marginBottom: 10, border: '1px solid #26354a' }}><p style={{ color: '#fb923c', fontWeight: 800, fontSize: 12, margin: 0 }}>{style.styleNumber}</p><h3 style={{ margin: '6px 0', fontSize: 15 }}>{style.name}</h3><p style={{ color: '#94a3b8', fontSize: 12 }}>{style.brand || 'Unassigned brand'} · {style.season || 'No season'}</p><div style={{ display: 'flex', flexWrap: 'wrap', gap: 5 }}>{style.tags?.map(t => <span key={t} style={{ color: '#cbd5e1', background: '#243247', padding: '3px 6px', borderRadius: 99, fontSize: 10 }}>#{t}</span>)}</div><select aria-label={`Move ${style.name}`} value={style.status} onChange={e => move(style, e.target.value)} style={{ marginTop: 12, width: '100%', background: '#0d1117', color: 'white', border: '1px solid #334155', padding: 7, borderRadius: 7 }}>{statuses.map(s => <option key={s} value={s}>Move to {label(s)}</option>)}</select>{style.status === 'fit_review' && <div style={{ display: 'grid', gap: 6, marginTop: 8 }}><button onClick={() => requestReview(style)} style={{ padding: 7, border: 0, borderRadius: 7, background: '#334155', color: 'white' }}>Request review</button><div style={{ display: 'flex', gap: 6 }}><button onClick={() => decide(style, 'approved')} style={{ flex: 1, padding: 7, border: 0, borderRadius: 7, background: '#166534', color: 'white' }}>Approve</button><button onClick={() => decide(style, 'changes_requested')} style={{ flex: 1, padding: 7, border: 0, borderRadius: 7, background: '#7c2d12', color: 'white' }}>Changes</button></div></div>}</article>)}</section>)}</div>
    {showNotifications && <div style={{ position: 'fixed', right: 24, top: 24, width: 'min(370px,90vw)', maxHeight: '80vh', overflow: 'auto', padding: 18, background: '#111b29', border: '1px solid #475569', borderRadius: 14, zIndex: 20, boxShadow: '0 18px 50px #000' }}><button onClick={() => setShowNotifications(false)} style={{ float: 'right', background: 'none', border: 0, color: '#94a3b8' }}>×</button><h3 style={{ marginTop: 0 }}>Notifications</h3>{notifications.length ? notifications.map(item => <div key={item._id} style={{ padding: '12px 0', borderTop: '1px solid #26354a' }}><strong style={{ fontSize: 13 }}>{item.title}</strong><p style={{ color: '#94a3b8', fontSize: 12, margin: '4px 0' }}>{item.message}</p></div>) : <p style={{ color: '#94a3b8' }}>You are all caught up.</p>}</div>}
    {showForm && <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,.65)', display: 'grid', placeItems: 'center', zIndex: 10 }}><form onSubmit={create} style={{ width: 'min(560px,92vw)', background: '#111b29', padding: 24, borderRadius: 16 }}><h2 style={{ marginTop: 0 }}>Create a style</h2><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>{[['name','Style name'],['styleNumber','Style number'],['season','Season'],['brand','Brand'],['category','Category'],['tags','Tags (comma separated)']].map(([key, placeholder]) => <input key={key} required={key === 'name' || key === 'styleNumber'} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} placeholder={placeholder} style={{ padding: 11, borderRadius: 8, border: '1px solid #334155', background: '#172233', color: 'white' }} />)}</div><div style={{ display: 'flex', justifyContent: 'end', gap: 10, marginTop: 18 }}><button type="button" onClick={() => setShowForm(false)} style={{ background: 'transparent', color: '#cbd5e1', border: 0 }}>Cancel</button><button style={{ background: '#ea580c', color: 'white', border: 0, borderRadius: 8, padding: '10px 15px', fontWeight: 800 }}>Create style</button></div></form></div>}
  </div>
}
